import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/cb/cc/3e/cbcc3eb6-9446-e67b-92d1-f9a9e311efcd/AppIcon-1x_U007emarketing-0-7-0-85-220.png/246x0w.webp" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
